window.RADAR_META = {
  asOf: "17 Aug 2026",
  categories: [
    { id: "all", label: "All" },
    { id: "targeting", label: "Targeting" },
    { id: "optimization", label: "Optimization" },
    { id: "measurement", label: "Measurement" },
    { id: "commerce", label: "Commerce surfaces" }
  ],
  categoryColors: {
    targeting: "#d7ff68",
    optimization: "#64d9bb",
    measurement: "#ad8dff",
    commerce: "#ff775f"
  },
  confidenceLabels: {
    disclosed: "Company disclosed / filed",
    dated: "Public but dated",
    estimate: "Secondary estimate",
    proxy: "Transaction proxy",
    unknown: "Not publicly disclosed"
  }
};

window.STARTUPS = [
  {
    id: "hightouch",
    company: "Hightouch",
    category: "targeting",
    subCategory: "Data activation + AI decisioning",
    status: "Private · Series D",
    x: 19,
    evidenceScore: 88,
    annualScale: 100,
    metricLabel: "Annual recurring revenue",
    metricValue: "$100M ARR",
    metricNote: "Company disclosed to TechCrunch, Apr 2026.",
    confidence: "disclosed",
    oneLiner: "Turns warehouse data into audiences, signals and agent-run marketing decisions.",
    pain: "Enterprise customer data is rich but trapped in warehouses, while audience and campaign decisions remain fragmented across tools and channels.",
    solution: "Reverse ETL, identity resolution, audience building and AI decisioning that sends context, conversion signals and actions into the tools marketers already use.",
    buyers: "Enterprise growth, CRM, lifecycle, data and marketing-operations teams.",
    customers: "Spotify, PetSmart, Chime, Grammarly, WHOOP, DoorDash and Warner Music Group.",
    monetization: "Enterprise SaaS with modular, usage-based contracts.",
    funding: "$150M Series D announced Apr 2026.",
    valuation: "$2.75B in Apr 2026.",
    investors: "Goldman Sachs Alternatives, Bain Capital Ventures, Amplify Partners, ICONIQ Capital, Sapphire Ventures and TD7.",
    proof: "The clearest current proof that a trusted data layer can support a $100M ARR decision interface.",
    angle: "Independent behavioural truth could improve audience quality and value signals while Hightouch owns connectors and orchestration.",
    watchout: "Its advantage is workflow distribution and data access, not only model quality.",
    sources: [
      { label: "$100M ARR · TechCrunch (2026)", url: "https://techcrunch.com/2026/04/15/hightouch-reaches-100m-arr-fueled-by-marketing-tools-powered-by-ai/" },
      { label: "Series D and valuation · Hightouch (2026)", url: "https://hightouch.com/blog/hightouch-funding-series-d" },
      { label: "Customers · Hightouch", url: "https://hightouch.com/customers" }
    ]
  },
  {
    id: "attain",
    company: "Attain",
    category: "targeting",
    subCategory: "Permissioned purchase data",
    status: "Private · Growth stage",
    x: 24,
    evidenceScore: 57,
    annualScale: null,
    metricLabel: "Absolute revenue / ARR",
    metricValue: "Not public",
    metricNote: "Company reported 150% YoY revenue growth in 2025.",
    confidence: "unknown",
    oneLiner: "Uses permissioned purchase data for audiences, measurement and in-flight outcomes.",
    pain: "Advertisers optimize against clicks and platform-reported proxies rather than verified purchases across retailers.",
    solution: "A consented consumer panel combining card, bank, receipt, SKU and declared data for audience activation, attribution, incrementality and optimization signals.",
    buyers: "Brands, agencies, media buyers and advertising platforms.",
    customers: "Partnerships include Publicis, PMG, Tombras, Google DV360, The Trade Desk, PubMatic and OpenX.",
    monetization: "Enterprise data licensing, audience activation and measurement services.",
    funding: "$25M growth round announced in 2022; secondary sources place total funding near $93M.",
    valuation: "Not publicly disclosed.",
    investors: "Mercato Partners, Core Innovation Capital, Lightbank, Starting Line and Silicon Valley Bank among named backers.",
    proof: "Strong growth and ecosystem partnerships, but no absolute annual revenue has been published.",
    angle: "The closest direct analogue for moving panel ground truth upstream into targeting and optimization.",
    watchout: "Panel reach, permission, freshness and match rates determine how much of the promise can be activated.",
    sources: [
      { label: "150% revenue growth · Attain (2025)", url: "https://www.attainoutcomes.com/news/attain-accelerates-to-150-annual-revenue-growth-with-strategic-innovations-and-elevated-partnerships" },
      { label: "Data asset · Attain", url: "https://www.attainoutcomes.com/our-data" },
      { label: "Company and business model · Attain", url: "https://www.attainoutcomes.com/about" }
    ]
  },
  {
    id: "black-crow",
    company: "Black Crow AI",
    category: "targeting",
    subCategory: "Predictive audiences + pLTV",
    status: "Private · Series A",
    x: 13,
    evidenceScore: 48,
    annualScale: 10.7,
    metricLabel: "Estimated annual recurring revenue",
    metricValue: "$10.7M est.",
    metricNote: "Latka estimate for 2025; not company disclosed.",
    confidence: "estimate",
    oneLiner: "Predicts customer value and feeds better signals into Meta, Klaviyo and storefronts.",
    pain: "DTC brands lose identity signals and waste acquisition spend on prospects with weak long-term value.",
    solution: "Server-side identity, predicted-LTV events, audience signals and personalized AI storefronts tied to ad intent.",
    buyers: "DTC growth, ecommerce and lifecycle teams, especially on Shopify.",
    customers: "Levain Bakery, Vegamour, DripDrop, Terra Kaffe, Clean Simple Eats and Bushbalm; earlier references include Solo Stove and Liquid I.V.",
    monetization: "SaaS subscription; public contract pricing is unavailable.",
    funding: "$25M Series A in 2022; $30M total disclosed at the time.",
    valuation: "Not publicly disclosed.",
    investors: "Imaginary Ventures, Primary Venture Partners, Bloomberg Beta, Interlock and Vast Ventures.",
    proof: "A close product analogue for passing predicted value back to the ad platform; the scale figure is only a third-party estimate.",
    angle: "Panel-calibrated LTV and audience quality could make the returned signals more independent and defensible.",
    watchout: "The product depends on customer-specific conversion volume and reliable server-side identity.",
    sources: [
      { label: "Series A · PR Newswire (2022)", url: "https://www.prnewswire.com/news-releases/black-crow-ai-raises-25-million-series-a-financing-to-make-enterprise-grade-machine-learning-available-to-all-301514302.html" },
      { label: "Product and customers · Black Crow AI", url: "https://www.blackcrow.ai/customer-stories" },
      { label: "ARR estimate · Latka", url: "https://getlatka.com/companies/blackcrow.ai" }
    ]
  },
  {
    id: "proxima",
    company: "Proxima",
    category: "targeting",
    subCategory: "Predictive data intelligence",
    status: "Private · Series A",
    x: 29,
    evidenceScore: 43,
    annualScale: null,
    metricLabel: "Absolute revenue / ARR",
    metricValue: "Not public",
    metricNote: "Company reported 400% revenue growth after launch.",
    confidence: "unknown",
    oneLiner: "Uses a shared consumer-data network to improve acquisition and retention for brands.",
    pain: "Consumer brands have thin first-party datasets and expensive paid acquisition, particularly before they reach scale.",
    solution: "Predictive audiences and benchmarks built from a network of B2C connections, activated in paid media.",
    buyers: "Growth-stage consumer brands and ecommerce performance teams.",
    customers: "Hint Water, mindbodygreen, Joe & The Juice and Venus et Fleur.",
    monetization: "Enterprise SaaS and data activation; public pricing is unavailable.",
    funding: "$12M Series A announced Apr 2024.",
    valuation: "Not publicly disclosed.",
    investors: "Mucker Capital, Aglaé Ventures, Great Oaks, Data Point, Broadway Venture Partners, FirstLook and Connexa.",
    proof: "A useful early-stage analogue for pooling behavioural data to improve audience acquisition; absolute scale is still opaque.",
    angle: "Representative panels could provide calibration and category context that a brand-sharing network lacks.",
    watchout: "Network data quality and privacy rights matter more than the size of the headline connection count.",
    sources: [
      { label: "Series A and revenue growth · Proxima (2024)", url: "https://www.proxima.ai/article/series-a" },
      { label: "Investors · Proxima (2024)", url: "https://www.proxima.ai/article/proxima-drives-toward-democratized-data-intelligence-q1-2024-update" }
    ]
  },
  {
    id: "moloco",
    company: "Moloco",
    category: "optimization",
    subCategory: "Value bidding + media optimization",
    status: "Private · Late stage",
    x: 37,
    evidenceScore: 91,
    annualScale: 200,
    metricLabel: "Annual revenue",
    metricValue: "$200M+ revenue",
    metricNote: "Company disclosed for FY2022; not ARR.",
    confidence: "dated",
    oneLiner: "Applies customer-specific ML to acquire high-value users beyond the walled gardens.",
    pain: "App marketers and marketplaces lack platform-grade machine learning for finding valuable users and monetizing first-party inventory.",
    solution: "Outcome-optimized bidding for mobile ads plus commerce-media and streaming monetization engines built on first-party data.",
    buyers: "Mobile app marketers, retailers, marketplaces, streaming services and publishers.",
    customers: "More than 1,000 advertisers were reported in 2023; public cases include Wayfair, W Concept, ManoMano and Fanatics Sportsbook.",
    monetization: "Media-spend margin for Moloco Ads; enterprise platform economics for commerce and streaming products.",
    funding: "$150M Series C in 2021; later investors joined through secondary transactions.",
    valuation: "$2B+ in a Jun 2023 secondary transaction.",
    investors: "Tiger Global, Fidelity, EDBI and earlier venture investors.",
    proof: "Large, profitable revenue proves value optimization can scale, but its economics are media revenue rather than SaaS ARR.",
    angle: "A source-of-truth provider should calibrate value and audience signals supplied to Moloco, not recreate its bidder.",
    watchout: "Revenue scale includes advertising economics and cannot be compared directly with software ARR.",
    sources: [
      { label: "Revenue and $2B+ valuation · Business Wire (2023)", url: "https://www.businesswire.com/news/home/20230629509254/en/Moloco-Welcomes-New-Investors-Into-Its-Cap-Table" },
      { label: "Series C · PR Newswire (2021)", url: "https://www.prnewswire.com/news-releases/moloco-closes-150-million-series-c-financing-led-by-tiger-global-to-bring-transparent-machine-learning-algorithms-to-all-301356860.html" },
      { label: "Current product scope · Moloco", url: "https://www.moloco.com/press-releases/ai-powered-performance-ctv" }
    ]
  },
  {
    id: "liftoff",
    company: "Liftoff Mobile",
    category: "optimization",
    subCategory: "Mobile acquisition + retargeting",
    status: "Public · Nasdaq LFTO",
    x: 69,
    evidenceScore: 96,
    annualScale: 685.7,
    metricLabel: "FY2025 annual revenue",
    metricValue: "$685.7M revenue",
    metricNote: "SEC-filed; not ARR. Public since Jun 2026.",
    confidence: "disclosed",
    oneLiner: "Optimizes mobile acquisition, creative and retargeting against post-install value.",
    pain: "App businesses need high-LTV users and durable ROAS despite privacy changes and signal loss.",
    solution: "Post-install events and revenue outcomes drive automated targeting, bidding, creative and retargeting across a scaled ad network.",
    buyers: "Mobile app growth teams and publishers.",
    customers: "Magazine Luiza, OTTO, Joom, Me2Zen, MyTona and Murka among published cases.",
    monetization: "Advertising spend / take-rate and publisher monetization, not subscription ARR.",
    funding: "Blackstone-controlled before IPO; General Atlantic acquired a minority stake in 2025.",
    valuation: "$4.3B transaction valuation in 2025; IPO valuation differed in 2026.",
    investors: "Blackstone and General Atlantic before the Jun 2026 public listing.",
    proof: "The cleanest filed scale evidence for value optimization, with nearly $686M FY2025 revenue.",
    angle: "Independent outcome calibration can improve the value events used by large optimizers without owning their auction.",
    watchout: "Network scale, supply relationships and media economics are central to the moat.",
    sources: [
      { label: "SEC prospectus and FY2025 revenue", url: "https://www.sec.gov/Archives/edgar/data/1850351/000119312526257410/iron_424b4_round_2.htm" },
      { label: "Product case · Liftoff", url: "https://www.liftoff.io/resources/case-study/magazine-luiza/" }
    ]
  },
  {
    id: "vibe",
    company: "Vibe.co",
    category: "optimization",
    subCategory: "Self-serve performance CTV",
    status: "Private · Series B",
    x: 63,
    evidenceScore: 76,
    annualScale: 100,
    metricLabel: "Revenue run-rate",
    metricValue: "$100M run-rate",
    metricNote: "Company disclosed Sep 2025; not ARR.",
    confidence: "disclosed",
    oneLiner: "Makes CTV buying look and feel like a self-serve performance-ad platform.",
    pain: "SMB and mid-market advertisers find television buying fragmented, slow and difficult to link to performance.",
    solution: "A self-serve CTV buying, targeting and measurement workflow with AI-assisted campaign setup and optimization.",
    buyers: "SMB, mid-market and performance advertisers moving into CTV.",
    customers: "More than 5,000 brands were cited in its 2025 funding announcement.",
    monetization: "Media-spend platform economics; the run-rate is revenue, not software ARR.",
    funding: "$50M Series B announced Sep 2025.",
    valuation: "$410M in Sep 2025.",
    investors: "Hedosophia, Elaia, Singular, QuantumLight and Illusian.",
    proof: "Shows that a simplified action interface can unlock fast CTV adoption and a $100M revenue run-rate.",
    angle: "A trusted TV panel can strengthen planning and outcome calibration while Vibe owns the buying surface.",
    watchout: "Its scale comes from managed media economics, so revenue quality differs from subscription software.",
    sources: [
      { label: "Series B, valuation and run-rate · GlobeNewswire (2025)", url: "https://www.globenewswire.com/news-release/2025/09/30/3158376/0/en/vibe-co-raises-50m-series-b-to-bring-ai-powered-hyper-targeted-advertising-to-tv.html" },
      { label: "Product · Vibe", url: "https://www.vibe.co/" }
    ]
  },
  {
    id: "voyantis",
    company: "Voyantis",
    category: "optimization",
    subCategory: "Predicted LTV decisioning",
    status: "Private · Growth stage",
    x: 43,
    evidenceScore: 53,
    annualScale: null,
    metricLabel: "Absolute ARR",
    metricValue: "Not public",
    metricNote: "Company said ARR tripled over two years.",
    confidence: "unknown",
    oneLiner: "Predicts customer LTV and pushes the signal into acquisition and lifecycle systems.",
    pain: "Growth teams optimize to cheap conversions rather than customers who become economically valuable over time.",
    solution: "Customer-level LTV predictions feed bidding, lifecycle and retention workflows before complete revenue histories exist.",
    buyers: "Consumer-app growth, lifecycle, finance and performance-marketing teams.",
    customers: "Consumer apps, fintech and subscription businesses; individual contract values are not public.",
    monetization: "Enterprise SaaS.",
    funding: "$41M round in Feb 2025; $60M total disclosed.",
    valuation: "Not publicly disclosed.",
    investors: "Intel Capital, Square Peg, Target Global, Jibe, Redseed, Alicorn, 20Growth and Essential.",
    proof: "Strong growth signal and credible capital, but no public absolute ARR.",
    angle: "Independent panels can calibrate predicted LTV where a customer's own data is sparse or biased.",
    watchout: "Inputs and models vary by advertiser, creating a real risk of bespoke implementation work.",
    sources: [
      { label: "Funding and ARR growth · Business Wire (2025)", url: "https://www.businesswire.com/news/home/20250211913390/en/Voyantis-Raises-%2441M-to-Help-Companies-Transition-to-Efficient-Growth-by-Focusing-on-the-RIGHT-Customers-at-the-RIGHT-Time" },
      { label: "Product · Voyantis", url: "https://www.voyantis.ai/" }
    ]
  },
  {
    id: "commerceiq",
    company: "CommerceIQ",
    category: "optimization",
    subCategory: "Retail ecommerce management",
    status: "Private · Series D",
    x: 53,
    evidenceScore: 67,
    annualScale: null,
    metricLabel: "Absolute revenue / ARR",
    metricValue: "Not public",
    metricNote: "Company reported revenue doubled in 2021.",
    confidence: "unknown",
    oneLiner: "Automates retail-media, sales and availability decisions across major marketplaces.",
    pain: "Consumer brands manage retail media, digital shelf, pricing and inventory through disconnected, manual workflows.",
    solution: "A unified retail ecommerce operating platform that applies ML to media, sales, content and supply-chain decisions.",
    buyers: "Global consumer-brand ecommerce, retail-media and sales teams.",
    customers: "Nestlé, Colgate, Whirlpool, Johnson & Johnson, Kellogg's, Bayer, KIND and more than 2,200 brands reported in 2022.",
    monetization: "Enterprise SaaS.",
    funding: "$115M Series D in 2022; $200M total disclosed.",
    valuation: "$1B+ in Mar 2022.",
    investors: "SoftBank Vision Fund 2, Insight Partners, Trinity Ventures, Shasta Ventures and Madrona.",
    proof: "Large enterprise adoption and unicorn financing validate retail decision automation, while public revenue remains opaque.",
    angle: "Category and demand signals can improve the decisions CommerceIQ automates across media and retail operations.",
    watchout: "Retailer-specific integrations and enterprise services can slow repeatability.",
    sources: [
      { label: "Series D, customers and valuation · CommerceIQ (2022)", url: "https://www.commerceiq.ai/press-releases/commerceiq-secures-115-million-investment-from-softbank-vision-fund-2-at-unicorn-valuation-to-revolutionize-retail-ecommerce-management" },
      { label: "Product · CommerceIQ", url: "https://www.commerceiq.ai/" }
    ]
  },
  {
    id: "stackline",
    company: "Stackline",
    category: "optimization",
    subCategory: "Retail intelligence + activation",
    status: "Private · Growth stage",
    x: 68,
    evidenceScore: 64,
    annualScale: null,
    metricLabel: "Absolute revenue / ARR",
    metricValue: "Not public",
    metricNote: "Customer and capital scale are disclosed, revenue is not.",
    confidence: "unknown",
    oneLiner: "Combines retail intelligence, ad automation and shopper analytics for consumer brands.",
    pain: "Brands cannot connect marketplace performance, retail media, shopper behaviour and operations in one decision system.",
    solution: "Retail-data products, forecasting, advertising automation and activation workflows across retailers and channels.",
    buyers: "Enterprise consumer-brand ecommerce and retail-media teams.",
    customers: "7,000 consumer brands; 83 of the top 100 consumer brands according to the company. Public examples include Sony, Levi's, General Mills and Starbucks.",
    monetization: "Enterprise software and data products.",
    funding: "$180M capital disclosed: $50M from Goldman Sachs and $130M from TA Associates.",
    valuation: "Not publicly disclosed.",
    investors: "Goldman Sachs Growth Equity and TA Associates.",
    proof: "Broad enterprise distribution is clear; a public annual-revenue figure is not.",
    angle: "Shopper and category panels could strengthen forecasting and cross-retailer demand intelligence.",
    watchout: "A wide suite can hide how much revenue is software, data, media services or implementation.",
    sources: [
      { label: "Capital and customer scale · Stackline", url: "https://www.stackline.com/about" },
      { label: "$50M investment and customer examples · Stackline (2020)", url: "https://www.stackline.com/news/stackline-receives-50-million-investment-from-goldman-sachs" }
    ]
  },
  {
    id: "appsflyer",
    company: "AppsFlyer",
    category: "measurement",
    subCategory: "Attribution + privacy cloud",
    status: "Private · Late stage",
    x: 89,
    evidenceScore: 95,
    annualScale: 400,
    metricLabel: "Annual recurring revenue",
    metricValue: "~$400M ARR",
    metricNote: "CEO disclosed for FY2023; public but dated.",
    confidence: "dated",
    oneLiner: "Independent attribution expanded into incrementality, clean rooms and data collaboration.",
    pain: "App-first advertisers need neutral attribution across platforms, devices and privacy regimes.",
    solution: "Mobile/web/CTV attribution, fraud prevention, incrementality, clean rooms, audiences and agentic data workflows.",
    buyers: "Global app-first marketing, growth, analytics and privacy teams.",
    customers: "Nike, eBay, HBO, Visa, Getir and Grubhub among public references; 28% of digitally present Fortune 500 companies in 2023.",
    monetization: "Subscription and usage-based enterprise SaaS.",
    funding: "$1B+ Series E reported by Axios in Jun 2026.",
    valuation: "$2.7B post-money reported in Jun 2026.",
    investors: "Moloco, Google, Meta and Unity in the reported 2026 round; General Atlantic and Salesforce Ventures previously.",
    proof: "The strongest private-company proof that independent measurement can reach several hundred million dollars of ARR.",
    angle: "Measurement becomes a platform when trusted data also supports activation, collaboration and model improvement.",
    watchout: "The 2026 investors include platforms it measures, which makes perceived independence an important governance question.",
    sources: [
      { label: "~$400M ARR · AppsFlyer CEO (2023)", url: "https://www.appsflyer.com/blog/ceo/challenges-opportunities-road-ahead/" },
      { label: "$1B+ Series E and valuation · Axios (2026)", url: "https://www.axios.com/2026/06/22/appsflyer-billion-moloco-google-meta-unity" },
      { label: "Earlier $200M ARR disclosure · AppsFlyer (2020)", url: "https://www.appsflyer.com/company/newsroom/pr/appsflyer-exceeds-200m-arr/" }
    ]
  },
  {
    id: "haus",
    company: "Haus",
    category: "measurement",
    subCategory: "Incrementality + causal decisioning",
    status: "Private · Growth stage",
    x: 94,
    evidenceScore: 58,
    annualScale: null,
    metricLabel: "Absolute revenue / ARR",
    metricValue: "Not public",
    metricNote: "At least $37M of announced financing across two rounds.",
    confidence: "unknown",
    oneLiner: "Productizes experiments, causal attribution and experiment-calibrated MMM.",
    pain: "Platform attribution overclaims credit, while rigorous incrementality tests are slow and require specialist teams.",
    solution: "Geo experiments, causal attribution, MMM and an AI copilot that turn lift evidence into budget decisions.",
    buyers: "Sophisticated consumer and enterprise marketing teams.",
    customers: "FanDuel, AG1, Sonos, Intuit, Dyson and Grubhub among public references.",
    monetization: "Custom enterprise SaaS plus expert support.",
    funding: "$17M Series A in 2023 and $20M additional financing in 2024.",
    valuation: "Not publicly disclosed.",
    investors: "Insight Partners, 01 Advisors, Baseline, Haystack, Upside, Octave and Mantis.",
    proof: "High-quality customer evidence validates causal decisioning, but public financial scale is unavailable.",
    angle: "A strong model for shipping directional decisions with explicit uncertainty and experimental calibration.",
    watchout: "Expert support and test design may constrain gross margin or repeatability if the workflow is not standardized.",
    sources: [
      { label: "$17M Series A · Haus (2023)", url: "https://www.haus.io/blog/17m-series-a-led-by-insight-partners" },
      { label: "$20M financing · Haus (2024)", url: "https://www.haus.io/blog/haus-announces-20m-raise-led-by-01-advisors" },
      { label: "Product · Haus", url: "https://www.haus.io/" }
    ]
  },
  {
    id: "measured",
    company: "Measured",
    category: "measurement",
    subCategory: "Incrementality + media planning",
    status: "Private · Growth stage",
    x: 82,
    evidenceScore: 60,
    annualScale: 15.1,
    metricLabel: "Estimated annual revenue",
    metricValue: "$15.1M est.",
    metricNote: "Latka estimate for 2024; not company disclosed.",
    confidence: "estimate",
    oneLiner: "Automates incrementality tests, calibrated MMM and budget optimization.",
    pain: "Brands cannot reconcile platform attribution or know which budget shifts create incremental sales.",
    solution: "Ongoing test-and-learn incrementality, benchmarks, MMM and media-plan recommendations.",
    buyers: "Enterprise DTC and omnichannel marketing teams.",
    customers: "Fabletics, Faherty, Ruggable, Vuori and Foot Locker among public cases.",
    monetization: "High-ACV subscription plus measurement support.",
    funding: "$21M growth investment announced in 2022.",
    valuation: "Not publicly disclosed.",
    investors: "Telescope Partners.",
    proof: "More than 120 DTC brands and $4.14B of experiments were cited by the company; the revenue figure remains a secondary estimate.",
    angle: "Shows the path from measurement to recurring allocation decisions rather than a one-off verification report.",
    watchout: "A service-heavy operating model could look like SaaS while retaining consulting economics.",
    sources: [
      { label: "Funding, clients and experiment scale · Measured", url: "https://www.measured.com/press/measured-secures-funding-to-solve-attribution-for-advertisers/" },
      { label: "Revenue estimate · Latka", url: "https://getlatka.com/companies/measured" },
      { label: "Product · Measured", url: "https://www.measured.com/" }
    ]
  },
  {
    id: "northbeam",
    company: "Northbeam",
    category: "measurement",
    subCategory: "MTA + MMM + signal feedback",
    status: "Private · Growth stage",
    x: 76,
    evidenceScore: 55,
    annualScale: null,
    metricLabel: "Absolute revenue / ARR",
    metricValue: "Not public",
    metricNote: "Public pricing starts near $1,500 per month.",
    confidence: "unknown",
    oneLiner: "Combines first-party attribution, MMM and feedback signals for ecommerce brands.",
    pain: "Performance teams see conflicting platform reports and cannot confidently reallocate spend each day.",
    solution: "First-party MTA, deterministic view-through measurement, MMM and Apex signals fed back into ad algorithms.",
    buyers: "Growth and enterprise ecommerce brands; enterprise tier targets more than $500K monthly media spend.",
    customers: "Timex, Dr. Squatch, Ridge, PetMeds and HexClad among public references.",
    monetization: "Subscription SaaS; public starter pricing begins around $1,500 per month with custom enterprise contracts.",
    funding: "$15M Series A in 2022 plus $15M growth investment in 2025.",
    valuation: "Not publicly disclosed.",
    investors: "HighPost Capital, Silversmith Capital Partners and earlier backers.",
    proof: "Clear repeatable packaging and public pricing, but no verified annual revenue figure.",
    angle: "A useful example of measurement becoming a daily allocation and platform-signal workflow.",
    watchout: "Its core customer base is concentrated in ecommerce and performance media rather than broad brand measurement.",
    sources: [
      { label: "Pricing · Northbeam", url: "https://www.northbeam.io/pricing" },
      { label: "2025 growth investment · Axios", url: "https://www.axios.com/2025/10/07/northbeam-video-views-attribution" },
      { label: "Product · Northbeam", url: "https://docs.northbeam.io/docs/what-is-northbeam" }
    ]
  },
  {
    id: "triple-whale",
    company: "Triple Whale",
    category: "measurement",
    subCategory: "Ecommerce data + AI workflow",
    status: "Private · Series B",
    x: 73,
    evidenceScore: 62,
    annualScale: null,
    metricLabel: "Absolute revenue / ARR",
    metricValue: "Not public",
    metricNote: "$65B+ of customer revenue tracked is not company revenue.",
    confidence: "unknown",
    oneLiner: "Turns ecommerce data, attribution and forecasting into an AI operating interface.",
    pain: "Ecommerce teams jump between fragmented dashboards and still need analysts to explain what changed and what to do.",
    solution: "Unified commerce data, attribution, forecasting, MMM and Moby agents that analyze and recommend actions.",
    buyers: "Ecommerce brands and agencies.",
    customers: "True Classic, Cozy Earth, Milk Bar, Brightland and Origin among public references.",
    monetization: "Revenue-tiered SaaS subscriptions.",
    funding: "$25M Series B in 2023; about $51.7M total disclosed across named rounds.",
    valuation: "Not publicly disclosed.",
    investors: "NFX, Elephant, Shopify and earlier investors.",
    proof: "The AI-interface pattern is credible and widely adopted; its own financial scale is not publicly verified.",
    angle: "A strong analogy for wrapping a trusted data layer in a conversational decision workflow.",
    watchout: "Recommendations only create advantage when the underlying causal and identity signals are reliable.",
    sources: [
      { label: "Series B · TechCrunch (2023)", url: "https://techcrunch.com/2023/02/02/triple-whale-raises-25m-for-its-smart-shopify-data-platform/" },
      { label: "Company and tracked scale · Triple Whale", url: "https://www.triplewhale.com/about" },
      { label: "Pricing · Triple Whale", url: "https://www.triplewhale.com/pricing" }
    ]
  },
  {
    id: "rockerbox",
    company: "Rockerbox",
    category: "measurement",
    subCategory: "Unified attribution suite",
    status: "Acquired · DoubleVerify",
    x: 86,
    evidenceScore: 65,
    annualScale: null,
    metricLabel: "Acquisition consideration",
    metricValue: "$85M exit",
    metricNote: "Headline consideration in Mar 2025; not revenue or ARR.",
    confidence: "proxy",
    oneLiner: "Unifies MTA, MMM, incrementality, planning and more than 100 integrations.",
    pain: "Direct-response advertisers need one view across attribution methods and channel data.",
    solution: "A shared data foundation for MTA, MMM, incrementality and planning, packaged for mid-market and performance teams.",
    buyers: "Mid-market and direct-response advertisers.",
    customers: "Away and WeightWatchers among published references.",
    monetization: "Enterprise subscription before acquisition.",
    funding: "Acquired by DoubleVerify in Mar 2025.",
    valuation: "$85M headline consideration; $82.3M net of acquired cash.",
    investors: "Now owned by DoubleVerify; prior venture financing is not the relevant current capital event.",
    proof: "The acquisition is strategic proof that verification incumbents want performance and activation exposure, not proof of standalone ARR.",
    angle: "A direct precedent for moving an established verification business toward performance decisioning.",
    watchout: "DoubleVerify initially expected only about $8M of partial-year 2025 revenue contribution.",
    sources: [
      { label: "Acquisition price · DoubleVerify SEC filing", url: "https://www.sec.gov/Archives/edgar/data/1819928/000110465926020499/dv-20251231x10k.htm" },
      { label: "Acquisition rationale · DoubleVerify SEC filing", url: "https://www.sec.gov/Archives/edgar/data/1819928/000155837025001812/dv-20250227xex99d2.htm" },
      { label: "Product · Rockerbox", url: "https://www.rockerbox.com/" }
    ]
  },
  {
    id: "alembic",
    company: "Alembic",
    category: "measurement",
    subCategory: "Causal attribution + forecasting",
    status: "Private · Growth stage",
    x: 79,
    evidenceScore: 61,
    annualScale: null,
    metricLabel: "Absolute revenue / ARR",
    metricValue: "Not public",
    metricNote: "$145M growth round announced Nov 2025.",
    confidence: "unknown",
    oneLiner: "Uses causal AI to connect cross-channel activity to revenue and future budgets.",
    pain: "Marketers cannot reliably identify which combination of TV, social, sponsorships and other activity caused revenue.",
    solution: "Causal inference across structured and unstructured media signals, producing attribution, forecasts and budget scenarios.",
    buyers: "Large enterprise marketing, finance and analytics leaders.",
    customers: "NVIDIA, Delta Air Lines, Mars, Texas A&M and North Sails among public references.",
    monetization: "Enterprise SaaS plus implementation and services.",
    funding: "$145M growth / Series B round announced Nov 2025.",
    valuation: "$645M reported in Nov 2025.",
    investors: "Prysm Capital, Accenture, Liquid 2, WndrCo and Silver Lake Waterman.",
    proof: "Customer and capital signals are strong, but the company has not published revenue or ARR.",
    angle: "A direct example of moving measurement to the beginning of budget allocation.",
    watchout: "Broad causal claims require careful validation; implementation may be data- and service-intensive.",
    sources: [
      { label: "Funding · Business Wire (2025)", url: "https://www.businesswire.com/news/home/20251117276054/en/Alembic-Raises-%24145-Million-to-Accelerate-Enterprise-Adoption-of-Causal-AI" },
      { label: "Valuation report · Reuters (2025)", url: "https://www.reuters.com/technology/artificial-intelligence/data-analytics-startup-alembic-raises-145-million-645-million-valuation-wsj-2025-11-17/" },
      { label: "Product · Alembic", url: "https://alembic.com/" }
    ]
  },
  {
    id: "tatari",
    company: "Tatari",
    category: "measurement",
    subCategory: "Convergent TV buying + measurement",
    status: "Private · Bootstrapped / undisclosed",
    x: 91,
    evidenceScore: 69,
    annualScale: 37.1,
    metricLabel: "Estimated annual revenue",
    metricValue: "$37.1M est.",
    metricNote: "Latka estimate for 2025; company reported 34% net-revenue growth in 2024.",
    confidence: "estimate",
    oneLiner: "Combines TV planning, buying, optimization and measurement in one workflow.",
    pain: "Linear and connected-TV buying remains fragmented, slow and difficult to optimize against business outcomes.",
    solution: "Direct and programmatic buying, attribution, planning and next-day optimization across linear and CTV.",
    buyers: "Performance brands and app-first advertisers entering television.",
    customers: "Made In, Daily Harvest, Fiverr, Teladoc, Rocket Money, Chime and Saatva.",
    monetization: "Media and platform/service fees, with optional managed services; not pure subscription ARR.",
    funding: "No announced institutional funding located; appears primarily bootstrapped.",
    valuation: "Not publicly disclosed.",
    investors: "No institutional investor list publicly confirmed.",
    proof: "The integrated TV workflow is commercially credible; absolute revenue remains an unaudited third-party estimate.",
    angle: "Shows how TV measurement becomes more valuable when attached to planning, buying and fast optimization.",
    watchout: "Buying and services economics make direct comparison with SaaS ARR inappropriate.",
    sources: [
      { label: "Platform · Tatari", url: "https://www.tatari.tv/brands/new-tv" },
      { label: "Measurement · Tatari", url: "https://www.tatari.tv/tv-measurement-attribution-tatari-platform" },
      { label: "Customer case · Tatari", url: "https://www.tatari.tv/case-studies/made-in" }
    ]
  },
  {
    id: "rokt",
    company: "Rokt",
    category: "commerce",
    subCategory: "Transaction-moment commerce media",
    status: "Private · Late stage",
    x: 50,
    evidenceScore: 98,
    annualScale: 600,
    metricLabel: "FY2024 annual revenue",
    metricValue: "$600M revenue",
    metricNote: "Company disclosed, +43% YoY; not ARR.",
    confidence: "disclosed",
    oneLiner: "Selects the next-best ad or offer inside checkout and post-purchase moments.",
    pain: "Commerce businesses under-monetize high-intent transaction moments, while advertisers struggle to reach verified buyers.",
    solution: "Real-time first-party transaction context drives personalized offers across carts, payments and confirmation pages.",
    buyers: "Large ecommerce sites, marketplaces, publishers and performance advertisers.",
    customers: "Uber, Live Nation, AMC, PayPal, Hulu, Staples, Fanatics, GoDaddy and HelloFresh.",
    monetization: "Dynamic CPC / auction-based ads with revenue share to commerce partners.",
    funding: "$325M Series E in 2021; $335M secondary transaction in 2025.",
    valuation: "$3.5B in Jan 2025 secondary transaction.",
    investors: "Tiger Global, Square Peg, Wellington, Whale Rock and other existing investors.",
    proof: "The strongest evidence that an embedded commercial widget can create hundreds of millions in transaction-style revenue.",
    angle: "Product, category and LTV ground truth could improve which offer appears in the commercial moment.",
    watchout: "Rokt's moat includes owned distribution, auction liquidity and network effects, not only data science.",
    sources: [
      { label: "Valuation and FY2024 revenue · Rokt (2025)", url: "https://www.rokt.com/blog/announcing-secondary-transaction-increasing-valuation-to-3-5-billion-and-appointment-of-anita-sands-to-the-board-of-directors/" },
      { label: "Series E · Rokt (2021)", url: "https://www.rokt.com/blog/rokt-secures-usd325-million-series-e-funding-round-led-by-tiger-global" },
      { label: "Rokt Ads product", url: "https://www.rokt.com/products/rokt-ads" }
    ]
  },
  {
    id: "fermat",
    company: "FERMÀT",
    category: "commerce",
    subCategory: "AI-native post-click commerce",
    status: "Private · Series B",
    x: 59,
    evidenceScore: 56,
    annualScale: null,
    metricLabel: "Absolute ARR",
    metricValue: "Not public",
    metricNote: "Company said ARR grew more than 5× after Series A.",
    confidence: "unknown",
    oneLiner: "Builds personalized landing, product and checkout experiences from shopper behaviour.",
    pain: "Ad intent is lost after the click, and commerce teams wait on multiple tools and engineering queues to test a better path.",
    solution: "An AI-native, no-code layer spanning behavioural insight, landing pages, merchandising, experimentation and checkout.",
    buyers: "Enterprise ecommerce, growth, merchandising and conversion teams.",
    customers: "BISSELL, Glossier, ILIA Beauty, GNC, OLLY, Away, Backcountry and Scotts Miracle-Gro.",
    monetization: "Enterprise SaaS with traffic / usage tiers.",
    funding: "$45M Series B in 2025; about $74M total disclosed.",
    valuation: "Not publicly disclosed.",
    investors: "VMG Partners, QED Investors, Greylock, Bain Capital Ventures and Courtside Ventures.",
    proof: "Strong funding, customer quality and ARR growth validate the action-surface thesis, although absolute ARR is private.",
    angle: "The clearest analogue for putting an AI/no-code experience on top of trusted behavioural data.",
    watchout: "The current moat is workflow speed and commerce data; independent population truth is not required for every use case.",
    sources: [
      { label: "Series B, customers and ARR growth · FERMÀT (2025)", url: "https://www.fermatcommerce.com/news/announcing-our-series-b-defining-the-next-era-of-commerce-with-ai" },
      { label: "Company and customers · FERMÀT", url: "https://www.fermatcommerce.com/about" },
      { label: "Product · FERMÀT", url: "https://www.fermatcommerce.com/" }
    ]
  },
  {
    id: "replo",
    company: "Replo",
    category: "commerce",
    subCategory: "No-code ecommerce experiences",
    status: "Private · Seed stage",
    x: 45,
    evidenceScore: 38,
    annualScale: null,
    metricLabel: "Absolute revenue / ARR",
    metricValue: "Not public",
    metricNote: "Do not infer ARR from merchant GMV or founder milestones.",
    confidence: "unknown",
    oneLiner: "A no-code and AI builder for Shopify landing pages, PDPs, quizzes and tests.",
    pain: "Ecommerce marketers cannot match every ad to a tailored page without designers and engineering support.",
    solution: "Visual and AI-assisted page creation, reusable components, experimentation and ad-to-page matching for Shopify.",
    buyers: "Shopify brands, ecommerce teams and agencies.",
    customers: "Magic Spoon, Loop Earplugs, TUSHY and POSSIBLE among published examples.",
    monetization: "Recurring subscription plus session / usage tiers.",
    funding: "$8.2M+ disclosed on the YC company profile.",
    valuation: "Not publicly disclosed.",
    investors: "Y Combinator, Figma, Vercel, General Catalyst, Infinity Ventures, MAGIC Fund and Base Case.",
    proof: "Strong product analogy for a 'Lovable for commerce' wrapper, but public financial proof is limited.",
    angle: "A source-of-truth layer could recommend and populate pages while Replo supplies the creation surface.",
    watchout: "No-code tooling is increasingly crowded and the product itself has no unique data moat.",
    sources: [
      { label: "Funding and investors · Y Combinator", url: "https://www.ycombinator.com/companies/replo" },
      { label: "Product and customers · Replo", url: "https://www.replo.app/" },
      { label: "Pricing · Replo", url: "https://www.replo.app/pricing" }
    ]
  },
  {
    id: "rebuy",
    company: "Rebuy",
    category: "commerce",
    subCategory: "Storefront personalization + offers",
    status: "Private · Series A",
    x: 66,
    evidenceScore: 63,
    annualScale: 10,
    metricLabel: "ARR range",
    metricValue: "$10M+ ARR",
    metricNote: "Founder said 'well into eight figures' in 2023; public but dated.",
    confidence: "dated",
    oneLiner: "Personalizes search, cart, checkout and post-purchase offers for Shopify brands.",
    pain: "Merchants leave conversion, AOV and post-purchase monetization on the table across generic store journeys.",
    solution: "Product recommendations, smart cart, checkout and post-purchase personalization plus third-party offers.",
    buyers: "Mid-market and enterprise Shopify merchants.",
    customers: "OLIPOP, Aviator Nation, Momofuku, Tecovas and Liquid Death.",
    monetization: "Core SaaS plus performance / revenue-share monetization for selected offer products.",
    funding: "$17M Series A in 2023; $21.4M total disclosed.",
    valuation: "Not publicly disclosed.",
    investors: "M13 and earlier investors.",
    proof: "A useful hybrid: recurring software revenue plus commerce-media commission economics.",
    angle: "Independent category and value data could make post-purchase recommendations less merchant-local and more predictive.",
    watchout: "Shopify concentration and app-platform dependency can limit distribution control.",
    sources: [
      { label: "Series A · Rebuy (2023)", url: "https://www.rebuyengine.com/news-room/series-a-announcement" },
      { label: "ARR range · TechCrunch (2023)", url: "https://techcrunch.com/2023/02/24/rebuy-commerce-personalization-series-a/" },
      { label: "Product · Rebuy", url: "https://www.rebuyengine.com/" }
    ]
  }
];
